### ISSUE TITLE
Weird Character on index.js

### ISSUE THREAD

**Issue by RickFrom1987** [kirjs/react-highcharts#16] opened 2015-08-04 20:29 UTC
visibilitySetter: function (value, key, element) {
            // IE9-11 doesn't handle visibilty:inherit well, so we remove the attribute instead (#2881, #3909)
            if (value === 'inherit') {
                element.removeAttribute(key);
            } else {
                element.setAttribute(key, value);
            }
        },

The problem is between the "} else" it shows up as
![solar_calculator](https://cloud.githubusercontent.com/assets/421170/9071883/a3f41a5c-3aac-11e5-8152-d2d9f8586e51.jpg)

Not sure what is causing this maybe an IDE issue? Maybe it is clashing with Babelify or Browserify or Gulp... but I think cleaning spaces in all your files and converting tabs to spaces before pushing to npm.

**Comment by kirjs** [comment] 2015-08-04 22:04
Can you write a bit more about where exactly this character showed up, and what did you do before that?
I can't see it in the `index.js` file in the repository.

**Comment by asegavac** [comment] 2015-08-06 17:14
Seeing this as well, not using Babelify or Gulp, though I am using browserify. Definitely looks like an encoding problem with highcharts - code shows it at https://github.com/highslide-software/highcharts.com/blob/master/js/highcharts.src.js#L2868

@RickFrom1987: adding charset="UTF-8" to your script tag should get it working again.

**Comment by RickFrom1987** [comment] 2015-08-06 17:15
@asegavac I will give that a shot. Thanks! Glad to see that I wasn't going crazy!

**Comment by kirjs** [comment] 2015-08-08 11:58
Is it reproducible? If so, how can I do that?

Which OS/Editors were you guys using?

**Comment by kirjs** [comment] 2015-09-05 20:58
I'm closing the issue, feel free to reopen if it comes again.

**Closed by kirjs** 2015-09-05 20:58 UTC
