### ISSUE TITLE
Uncaught TypeError: Cannot read property 'chart' of undefined

### ISSUE THREAD

**Issue by realbugger** [kirjs/react-highcharts#119] opened 2016-03-29 06:57 UTC
First of all, really nice job for wrapping highcharts as a react component, exactly what I've been looking for!

Following the instruction, I was able to get it up and run pretty easily. Everything works as expected, except the browser keeps throwing the following error whenever page reflows.
```
Uncaught TypeError: Cannot read property 'chart' of undefined
    hb.reflow @highcharts.js:222
    (anonymous function) @ReactHighcharts.js:1
```
Although it doesn't seem to cause any real problem (the charts redraw without issue), I'd love to see a way to workaround the error. Here is the code for reference, which is pretty much the bare minimal for showing a line chart.

```
import React, {Component} from 'react';
import ReactHighcharts from 'react-highcharts';

export default class HighchartLine extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    const config = {
      ...... // skipping the detail here for saving space
    };
    return (<ReactHighcharts config = {config} />);
  }
}
```

**Comment by kirjs** [comment] 2016-03-30 03:26
Hi Pang, thanks for the issue.
Can you try reproducing it in [jsbin](http://qs.js.org/jsbin/react-highcharts?autostart)?

**Comment by jeron-diovis** [comment] 2016-03-30 08:40
I can't provide jsbin, but confirm this issue. It fails [here](https://github.com/kirjs/react-highcharts/blob/master/src%2FchartsFactory.jsx#L27). 

The strange thing is that while executing `renderChart ` method, `this.chart` is normal chart instance, but in rAF callback all instance props disappear:

---

![screenshot 2016-03-30 11 39 38](https://cloud.githubusercontent.com/assets/2756868/14136495/c1d99d3c-f66b-11e5-9295-eea6626ace51.png)

---

![screenshot 2016-03-30 11 38 53](https://cloud.githubusercontent.com/assets/2756868/14136496/c1da1280-f66b-11e5-917e-7cf1708291f3.png)

---

If this can help, my js is processed with following:

```json
    "babel-loader": "^6.2.4",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-1": "^6.5.0",
```

**Comment by jeron-diovis** [comment] 2016-03-30 08:50
In version 8.0.0 this issue is not reproducible.

**Comment by kirjs** [comment] 2016-03-30 09:21
This looks curious, in which version is it broken?

**Comment by jeron-diovis** [comment] 2016-03-30 09:25
@kirjs I checked 8.0.3.

**Comment by kirjs** [comment] 2016-03-30 11:12
Looks interesting, I'll take a look. I'm travelling ATM, so it may take a few weeks.

**Comment by Matsemann** [comment] 2016-03-30 15:12
We have a similar issue. For us it happens because the reflow-call inside `requestAnimationFrame` happens after `componentWillUnmount`, so checking if the chart still exists in the callback might be a good idea.

What triggers this in our case is that it mounts->unmounts->mounts quickly. If that is an error on our part I'm currently figuring out.

**Comment by realbugger** [comment] 2016-04-01 18:41
Looks like the fix is on the way. Will check back once it's out.

**Comment by kirjs** [comment] 2016-04-01 21:32
This should be fixed in 8.1.0, thanks to @dbergey

**Comment by Danita** [comment] 2016-04-02 23:38
Is there anything in special one should do? Because I just updated to 8.1.0 and the message just came out again.

**Comment by Matsemann** [comment] 2016-04-04 11:41
this.chart wont be null/undefined after unmount, it will be an object without properties (containing a lot of prototypes, though). So checking if `this.chart.options` or something similar exists may be better.

**Comment by kirjs** [comment] 2016-04-04 12:09
I'm still travelling and not able to fix/test for the next couple of weeks, PRs welcome.

**Comment by dbergey** [comment] 2016-04-04 18:45
I have code where I just wrapped that line in a try/catch. Is that acceptable for a PR?

**Comment by kirjs** [comment] 2016-04-04 18:54
If you put a huge TODO comment, this might work as a temporary solution. 
If you have a chance can you maybe try 
```javascript 
if(this.chart && this.chart.options ...
```
as per @Matsemann suggestion?

**Comment by kirjs** [comment] 2016-04-05 05:42
@Matsemann @Danita 8.1.1 should fix it now (if not, I'll find some time this week to make it work)

**Closed** 2016-04-05 17:53 UTC

**Comment by Danita** [comment] 2016-04-08 15:39
Yay it works perfectly now! Thanks a lot!
