### ISSUE TITLE
Click event not firing

### ISSUE THREAD

**Issue by tquetano-r7** [kirjs/react-highcharts#21] opened 2015-08-18 16:05 UTC
As title says, my click event is not firing with. The load event is firing (so I know the events object is being passed), however click does not fire. Is there something I'm missing?

I'm establishing it on the page as such:

```
import $ from "jquery"; // you should probably note in the documentation that jQuery is a dependency
import Highcharts from "react-highcharts";
```

My config (generified a bit):

```
var config = {
    chart:{
        events: {
            click: function (event) {
                // this doesn't work
                console.log(this);
            },
            load:function(){
                // this works
                console.log(this);
            }
        },
        // this is ignored
        options3d:{
            alpha:45,
            beta:0,
            enabled:true
        },
        type:"pie"
    },
    plotOptions:{
        pie:{
            cursor:"pointer",
            depth:35,
            dataLabels:{
                enabled:true,
                format:"{point.name}"
            }
        }
    },
    series:[{
        data:zeDataStuffz,
        name:"Le pie",
        type:"pie"
    }],
    title:{
        text:""
    },
    tooltip:{
        pointFormat:"Occurrences: <b>{point.y}</b>"
    }
};
```

Then its called:

```
<Highcharts config={config} ref="pieChart"/>>
```

The data is being passed correctly and the chart renders (although without 3D? minor issue compared to click), however click is not firing.

**Comment by kirjs** [comment] 2015-08-28 18:07
Thanks for reporting, I'll take a look over the weekend

**Comment by kirjs** [comment] 2015-09-05 20:57
Tony, I tried your example, and click worked perfectly well for me.
Is it still an issue?

**Comment by kirjs** [comment] 2015-09-08 14:28
Closing as I can't reproduce it, feel free to reopen

**Closed by kirjs** 2015-09-08 14:28 UTC
