### ISSUE TITLE
It's not working - how to implement highcharts?

### ISSUE THREAD

**Issue by gos-sebastian** [kirjs/react-highcharts#15] opened 2015-07-24 13:25 UTC
Sory for no description but I've double click enter :/

**Comment by joshhornby** [comment] 2015-07-24 13:26
Whats not working and what have you tried?

**Comment by Kureev** [comment] 2015-07-24 13:31
Please, can you provide more info about your issue: browser, version of react, version of react-highcharts and a stack trace you have.

**Comment by gos-sebastian** [comment] 2015-07-24 13:40
I've made npm install react-highcharts --save into my reactJS project and after that I'm trying to implement it.

I have index.html file in which i display app.js. Inside app.js I render my Main component. My Main component look like this:
var React = require('react');
var Highcharts = require('react-highcharts');

var config = {
  /* HighchartsConfig */
};
var Main = React.createClass({
  getInitialState: function() {
    return {
        config: {}
    };
  },
  componentDidMount: function() {
    var config = {
    
        xAxis: {
            categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        },
    
        series: [{
            data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
        }]
    
    };
    this.setState({
       'config':config,
    });
  render: function() {
		return (
				<div id="main">
              <Highcharts config = {this.state.config} />
				</div>
		);
	}
});

module.exports = Main;

**Comment by gos-sebastian** [comment] 2015-07-24 14:52
On console I get this error:
```
"Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref."
```

**Comment by kirjs** [comment] 2015-07-25 22:50
Hi Sebastian, 

I tried to run the example you provided, and was having a hard time of reproducing the error, several things here: 
1) You have a file called `Main.js`, but I don't see where you actually require it
2) There are several syntactic errors, e.g. ` render: function() {` seems to be in the body of `componentDidMount` function. 

Could you please take a look at the code, and update the example once you have a second?

**Comment by gos-sebastian** [comment] 2015-07-28 10:23
I have large app and wanted to give an example, sory for mistakes. Here are files after corrections. What is interesting - I've implemented it on other app using import/export not require and I had no problem with that.

Here are my files

```
// App.js
var React = require('react');
var Highcharts = require('react-highcharts');

var config = {
  /* HighchartsConfig */
};
var App = React.createClass({
  getInitialState: function() {
    return {
        config: {}
    };
  },
  componentDidMount: function() {
    var config = {

        xAxis: {
            categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        },

        series: [{
            data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
        }]

    };
    this.setState({
       'config':config,
    });
	},
  render: function() {
        return (
                <div id="chart">
              <Highcharts config = {this.state.config} />
                </div>
        );
    }
});

module.exports = App;
```
```
// app.js
var React = require('react');
var App = require('./components/App');

React.render(
  <App />,
  document.getElementById('main')
);
```
```
// index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
		<title>MyApp</title>
		<link href="node_modules/bootstrap/dist/css/bootstrap.css" type="text/css" rel="stylesheet" />
		<link href="src/css/styles.css" type="text/css" rel="stylesheet" />
    <script src="node_modules/underscore/underscore-min.js"></script>
    <script src="node_modules/react/dist/react.js"></script>
    <script src="node_modules/jquery/dist/jquery.min.js"></script>

	</head>
	<body>
		<div id="main" class="container">
			<!-- The App will be rendered here -->
		</div>
		<!-- Our compiled JavaScript source file -->
    <script src="dist/app.js"></script>
	</body>
</html>
```
I'm using 
```
  "dependencies": {
    "griddle-react": "^0.2.13",
    "jquery": "^1.11.3",
    "react": "^0.13.2",
    "react-highcharts": "^1.0.2",
    "underscore": "^1.8.3"
  },
  "devDependencies": {
    "bootstrap": "^3.3.5",
    "browserify": "^6.2.0",
    "browserify-shim": "^3.2.0",
    "http-server": "^0.6.1",
    "reactify": "^0.15.2",
    "uglify-js": "^2.4.20",
    "watchify": "^2.1.1"
  },
```

**Comment by gos-sebastian** [comment] 2015-07-28 12:49
I found the problem however I'm not able to call component inside of another component which in this case is useless.
```
var React = require('react/addons'); 
```
instead of
```
var React = require('react'); 
```

and then I'm able to call 
```
React.render(<Highcharts config = {config}></Highcharts>, document.body);
```
but only from app.js

When I'm trying to call Highcharts component from my own component I still get this error
```
"Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. 
This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, 
was not created inside of another component's `render` method). Try rendering this component inside
of a new top-level component which will hold the ref."
```

**Comment by kirjs** [comment] 2015-08-04 02:03
Hello, 
I tried to reproduce it again, but everything worked for me. 

2 things I did differently: 
1) I did not include react in the html file, as it's already included in JS. 
2) I used webpack as I'm not familiar with your browserify setup, you can try using browserify to see if that's what's causing the issue. 

I created a separate branch you could play with: 
https://github.com/kirjs/react-highcharts/commit/12c280d0abefaf943641beaefb11a573fec180a6

**Comment by nickbrit** [comment] 2015-08-15 20:19
It can be useful:

"I encountered this error when a component module I was using had it's own react dependency installed. So I was using multiple versions of React.

Make sure NOT to list react under dependencies in your package.json. This is why we have peerDependencies ;-)"
http://stackoverflow.com/questions/28519287/what-does-only-a-reactowner-can-have-refs-mean

**Comment by kirjs** [comment] 2015-08-29 19:24
Closing, feel free to reopen if needed

**Closed by kirjs** 2015-08-29 19:24 UTC
