### ISSUE TITLE
Error on hover - Cannot read property 'series' of undefined

### ISSUE THREAD

**Issue by dergachevm** [kirjs/react-highcharts#181] opened 2016-08-18 18:36 UTC
I don't know how to reproduce my code with JSBin, but its there:
http://jsbin.com/qapejokeye/edit?js,output

Screen with error:
![image](https://cloud.githubusercontent.com/assets/5065317/17785705/8896f928-658a-11e6-86ac-14b8ec76000d.png)

How i can resolve this error?
This happen only when i using `solidgauge`

**Comment by laopunk** [comment] 2016-08-31 12:45
Same issue as @dergachevm, came up to the same conclusions when looking at the source code.
It indeed is not reproducible in a vanilla highcharts environment, it only happens when using react-highcharts.

**Comment by kirjs** [comment] 2016-09-10 15:57
Can someone help me reproduce?
Seems to work for me in jsbin
 http://jsbin.com/xabenuviho/3/edit?html,js,output

**Comment by laopunk** [comment] 2016-09-14 12:53
I can't reproduce this on jsbin ... :-(
The issue seems to be linked to the npm package then ..

See attached a test case to reproduce the issue (this is a stripped down version of my dev environment so please excuse the unused variables)

- Just open dist/index.html and look at the console output.
- If you want to look at the source, they are all in the src directory
- I have also provided the package.json and gulpfile for you to reproduce the build process if you wish (just type gulp to build from src)

JSBIN working version:
http://jsbin.com/nicesuxovi/edit?html,js,output

Hope this will help ... good luck with the debugging :-)
[highcharts.zip](https://github.com/kirjs/react-highcharts/files/472038/highcharts.zip)

**Comment by kirjs** [comment] 2016-09-15 02:30
Thanks, will try to take a look over the weekend

**Comment by kirjs** [comment] 2016-09-18 16:57
@laopunk would it be possible to get the same zip but unminimized?

**Comment by laopunk** [comment] 2016-09-19 08:41
Hi @kirjs thanks for having a look,

The minified sections are actually coming from the highcharts node module itself, but I have unminified the main block to help with the troubleshooting.

Let me know if you need anything else
[highcharts_2.zip](https://github.com/kirjs/react-highcharts/files/479544/highcharts_2.zip)

**Comment by kirjs** [comment] 2016-09-19 16:37
Hey @laopunk, I looked at the code, and I don't see you actually using react-highcharts. It's included in the codebase, but eventually you just end up applying highcharts to the DOM element manually. 
Am I missing something?

The code I'm looking for would look like this:
```jsx
<ReactHighcharts config = "..."/>
```

**Comment by laopunk** [comment] 2016-09-30 14:25
Hi @kirjs ,
In this example you're right I am not, I was just trying to get something out quickly ...
Now the good news is that it indeeds isolates your library out of the equation :-)

As an aside, I have just pulled highcharts v4.2.7 today and the issue has disappeared, so they must have fixed it on their side somehow ...
There seem to be a v5.0.0 also released yesterday, I haven't had the chance to play with it yet.

As far as I am concerned this issue can be closed, are you happy with this @dergachevm ?

**Comment by dergachevm** [comment] 2016-10-04 22:43
@laopunk with 4.2.7 error was dissapeared, thanks

**Comment by kirjs** [comment] 2016-10-14 01:52
Thanks, closing

**Closed by kirjs** 2016-10-14 01:52 UTC
