### ISSUE TITLE
ReferenceError: requestAnimationFrame is not defined

### ISSUE THREAD

**Issue by freddiecabrera** [kirjs/react-highcharts#148] opened 2016-05-22 06:14 UTC
Where exactly do you put 
```
if(!Highcharts){
  global.highcharts = require('react-highcharts/src/fakeHighcharts.js');
}
```
for node rendering? I have tried several different ways but I am not having any luck. Is there a complete example of this? Thanks in advanced.

**Comment by kirjs** [comment] 2016-05-23 15:34
The example is a bit outdated, but should still work. 
You should put it at the point where highcharts has to be required. 
Better alternative would be to provide fake highcharts as highcharts dependency during in your build system. 

Regarding the error you're getting, try creating requestAnimationFrame in `fakeHighcharts.js`:
```js
var requestAnimationFrame = function(){};
```

If it works, please create a PR, or let me know, and I'll add it manually.

**Comment by freddiecabrera** [comment] 2016-05-23 18:15
This is what my component currently looks like. I tried adding `var requestAnimationFrame = function(){};`
to `fakehighcharts.js` but I still got the error. Maybe I am doing it wrong. 
```

import React from 'react'
import Highcharts from 'highcharts'
if (!Highcharts) {
  global.highcharts = require('react-highcharts/src/fakeHighcharts.js')
}
import ReactHighcharts from 'react-highcharts'
import { performanceScoreByMatch, performanceScoreCumulative } from '../../temp/guardado'

const date = performanceScoreByMatch.attacking.map(data => data.date)

const performanceScoreByMatchAttackingScore = performanceScoreCumulative.attacking.map(data => JSON.parse(data.score))
const performanceScoreByMatchDefensiveScore = performanceScoreCumulative.defensive.map(data => JSON.parse(data.score))
const performanceScoreByMatchOverallScore = performanceScoreCumulative.overall.map(data => JSON.parse(data.score))
const performanceScoreByMatchPossesionScore = performanceScoreCumulative.possesion.map(data => JSON.parse(data.score))

// const performanceScoreCumulativeAttackingScore = performanceScoreCumulative.attacking.map(data => data.score)
// const performanceScoreCumulativeDefensiveScore = performanceScoreCumulative.defensive.map(data => data.score)
// const performanceScoreCumulativeOverallScore = performanceScoreCumulative.overall.map(data => data.score)
// const performanceScoreCumulativePossesionScore = performanceScoreCumulative.possesion.map(data => data.score)

const config = {
  chart: {
    backgroundColor: '#0e0e13',
    type: 'areaspline'
  },
  title: {
    text: 'Performance Score By Match'
  },
  xAxis: {
    categories: date
  },
  plotOptions: {
         areaspline: {
             fillOpacity: 0.1
         }
     },
  series: [
    { name: 'Attacking', data: performanceScoreByMatchAttackingScore, color: 'green' },
    { name: 'Defensive', data: performanceScoreByMatchDefensiveScore, color: 'red' },
    { name: 'Possesion', data: performanceScoreByMatchPossesionScore, color: 'yellow' },
    { name: 'Overall', data: performanceScoreByMatchOverallScore, color: 'blue' }
  ]
}

const Chart = React.createClass({
  render () {
    return (
      <div>
        <ReactHighcharts config={config} />
      </div>
    )
  }
})

export default Chart
```

**Comment by kirjs** [comment] 2016-05-24 01:21
how about `global.requestAnimationFrame = function(){};`?

**Comment by freddiecabrera** [comment] 2016-05-24 02:08
Nothing seems to be making it work. The chart gets rendered but it gets that error 

`bundle.js:33065 Uncaught TypeError: Cannot read property 'requestAnimationFrame' of undefinedrenderChart @ bundle.js:33065HighchartsChart_componentDidMount @ bundle.js:33073notifyAll @ bundle.js:6436close @ bundle.js:16224closeAll @ bundle.js:6797perform @ bundle.js:6744batchedMountComponentIntoNode @ bundle.js:2637perform @ bundle.js:6731batchedUpdates @ bundle.js:10781batchedUpdates @ bundle.js:6236_renderNewRootComponent @ bundle.js:2831ReactMount__renderNewRootComponent @ bundle.js:1425_renderSubtreeIntoContainer @ bundle.js:2905render @ bundle.js:2925React_render @ bundle.js:1425(anonymous function) @ bundle.js:63__webpack_require__ @ bundle.js:20(anonymous function) @ bundle.js:40(anonymous function) @ bundle.js:43`

**Comment by freddiecabrera** [comment] 2016-05-24 02:12
Here is the Repo if you would like to check it out https://github.com/freddiecabrera/ullibol-client

**Comment by freddiecabrera** [comment] 2016-05-25 07:46
I got this to work by removing any mention about requestAnimationFrame. I am doing server rendering and I did not have to do
```
 if (!Highcharts) {
  global.highcharts = require('react-highcharts/src/fakeHighcharts.js')
}
```
I just did `import ReactHighcharts from 'react-highcharts'`. Is there a way I can get a version without requestAnimationFrame?

**Comment by rxt2012kc** [comment] 2016-05-26 07:16
I encounter the same problem as ahead, when I require('react-highcharts/dist/ReactHighcharts'), the console shows ReferenceError: requestAnimationFrame is not defined

**Comment by kirjs** [comment] 2016-06-09 17:32
Let me know if you still need help with it, I'll ping you on IM and we'll figure it out.

**Comment by freddiecabrera** [comment] 2016-06-09 17:36
I just completely removed anything having to do with requestAnimationFrame and I got it to work.

**Comment by kirjs** [comment] 2016-06-11 15:33
Which version of node did you use?

**Comment by jontore** [comment] 2016-06-23 08:17
I've also encountered this problem when I package my application, and react-highcharts is packaged with webpack.

**Comment by chevin99** [comment] 2016-06-24 18:28
Same problem for me as @jontore:

> I've also encountered this problem when I package my application, and react-highcharts is packaged with webpack.

**Comment by freddiecabrera** [comment] 2016-06-24 18:34
I was using node 4.3.0

@jontore @chevin99 if you guys would like to get passed it just go through all the files and manually remove anything having to do with requestAnimationFrame. I am sure that is not the best way to do it but it worked for me.

**Comment by kirjs** [comment] 2016-06-24 19:21
Can somebody help me reproduce that?

**Comment by chevin99** [comment] 2016-06-24 19:42
@kirjs here you go:

app.js -

```
let React = require('react')
let ReactDOM = require('react-dom')
let ReactHighcharts = require('react-highcharts')

let Chart = React.createClass({
  render: function () {
    let config = {
      series: [{
        name: 'A',
        data: [1, 2, 3, 4]
      }, {
        name: 'B',
        data: [5, 4, 3, 2]
      }]
    }

    return <ReactHighcharts config={config}/>
  }
})

ReactDOM.render(<Chart/>, document.getElementById('app'))
```

In my webpack config I use the babel loader:

```
module: {
    loaders: [
      {
        test: /\.js?$/,
        loader: 'babel',
        query: {
          presets: ['es2015', 'react', 'stage-0']
        }
      }
    ]
  }
```

Hope that helps.  Thanks.

**Comment by kirjs** [comment] 2016-06-26 18:12
I tried to reproduce again, but couldn't. 
Which browser/environment? which react-highcharts version? What's the exact error message?

**Comment by chevin99** [comment] 2016-06-27 12:21
Browser: Chrome Version 51.0.2704.103 (64-bit)
react-highcharts version 8.3.3

There error is just `Uncaught TypeError: Cannot read property 'requestAnimationFrame' of undefined`

I believe the problem is line 33 in **chartsFactory.jsx**:

`global.requestAnimationFrame && requestAnimationFrame(()=>{`

`global` isn't defined in the browser.  If I update the code to have `global` default to `window` the error goes away.

**Comment by kirjs** [comment] 2016-06-28 02:09
Should be fixed in 8.4.1, feel free to reopen if not

**Closed by kirjs** 2016-06-28 02:09 UTC
