### ISSUE TITLE
highcharts annotations with npm

### ISSUE THREAD

**Issue by jk171505** [kirjs/react-highcharts#379] opened 2018-02-06 20:37 UTC
I'm trying to make such configuration work:
http://jsbin.com/foyawejoca/edit?html,js,output

but with modules installed via npm:
`import React from 'react';`
`import ReactHighcharts from 'react-highcharts';`
`import annotations from 'highcharts-annotations';`
...
`    return <div>`
`        <ReactHighcharts config={_mergedConfig}/>`
`    </div>`

For some reason this doesn't work... How this should be configured?

**Comment by ilyjs** [comment] 2018-02-06 20:49
Duplicate of #240

**Closed by ilyjs** 2018-02-06 20:49 UTC
